name: CI

on:
  push:
    branches:
      - main
      - dev

jobs:
  CI:
    runs-on: windows-latest
    steps:
      - name: check out repository
        uses: actions/checkout@v2

      - name: set up python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: install poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: "1.1.12"

      - name: install dependencies
        run: poetry install

      - name: isort
        run: poetry run isort .

      - name: black
        run: poetry run black .

      - name: pylint
        run: poetry run pylint tally tests -d fixme

      - name: mypy
        run: poetry run mypy

      - name: pytest
        run: poetry run pytest
